### ISSUE TITLE
mining.ini within installed package

### ISSUE THREAD

**Issue by ayr-ton** [avelino/mining#230]
When build the mining for production, it doesn't copy the mining.ini file within the package.

Suggestions:
- Under setup(), include a static session "data_files" and add "mining.ini" to this.
- A different default place for the conf files for production installs, that doesn't depend from PROJECT_PATH variable 
- Other?

**Comment by avelino** [comment]
Very nice, It had left the process simpler.

You send PR?

**Comment by ayr-ton** [comment]
Yes, sure.
Which one of the suggestions do you guys prefer? 
Can I choose?

**Comment by avelino** [comment]
Stay so to implement the best solution!

**Comment by ayr-ton** [comment]
@avelino I choose the first suggestion. In the future we can discuss a better place for the conf, but it solves for now.
