### ISSUE TITLE
Error: 500 Internal Server Error at login.html

### ISSUE THREAD

**Issue by lerrua** [avelino/mining#248]
Hi there!

After install OpenMining I can't access login page, and Yes my frontend repository has been updated with theses files.

![screen shot 2015-06-23 at 4 54 33 pm](https://cloud.githubusercontent.com/assets/154603/8315655/9ade6c06-19c8-11e5-81d8-e991b0e9a036.png)

**Comment by lerrua** [comment]
This PR #250 will fix this issue too

**Comment by ayr-ton** [comment]
Tested. The PR #250 fixed this.
